
## Banking Transactions Dataset - Data Cleaning Scripts
=====================================================
 
This module provides ready-to-use functions for cleaning the 
dirty banking dataset with duplicates and missing values.
 
Usage:
    from data_cleaning_scripts import *
    
    df = pd.read_csv('banking_transactions_200k_dirty.csv')
    df_clean = clean_all(df)
    df_clean.to_csv('banking_transactions_200k_clean.csv', index=False)

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
from typing import Tuple, Dict, List

# import the Banking dataset 
by use of pandas

In [2]:
df = pd.read_csv(r"C:\Users\bhara\Documents\Projects\AI Data Analyst\banking_transactions_200k_dirty.csv")

check the head

In [3]:
df.head()

,Transaction_ID,Customer_ID,Customer_Name,Gender,Age,Occupation,Monthly_Income,Account_Type,Account_Status,Customer_Segment,...,City,State,Transaction_Date,Transaction_Time,Day_of_Week,Device_Type,Login_Location,Transaction_Status,Fraud_Flag,Remarks
0,TXN00010391,CUST000260,Manoj Banerjee,Female,51.0,Trader,200000.0,Savings,Dormant,Silver,...,Mumbai,Maharashtra,2025-12-18,11:22:53,Thursday,Mobile,Mumbai,Success,No,Transaction completed successfully
1,TXN00030704,CUST000768,Ravi Mahajan,Female,74.0,Designer,500000.0,Savings,Inactive,Silver,...,Lucknow,Uttar Pradesh,2024-04-19,06:31:56,Friday,Branch Terminal,Lucknow,Success,No,Transaction completed successfully
2,TXN00081468,CUST002037,Siddharth Nair,Male,26.0,Trader,30000.0,Student,Closed,Premium,...,Ahmedabad,Gujarat,2025-02-11,22:46:47,Tuesday,ATM,Ahmedabad,Success,No,Transaction completed successfully
3,TXN00154796,CUST003870,Krishna Sharma,Female,74.0,Pharmacist,100000.0,Salary,Closed,Standard,...,Lucknow,Uttar Pradesh,2024-07-24,06:46:40,Wednesday,Tablet,Lucknow,Success,No,Transaction completed successfully
4,TXN00196352,CUST004909,Anjali Ghosh,Female,23.0,Housewife,150000.0,Current,Dormant,Premium,...,Bengaluru,Karnataka,2024-02-25,20:53:05,Sunday,Desktop,Bengaluru,Success,No,Transaction completed successfully

Check the tail

In [4]:
df.tail()

,Transaction_ID,Customer_ID,Customer_Name,Gender,Age,Occupation,Monthly_Income,Account_Type,Account_Status,Customer_Segment,...,City,State,Transaction_Date,Transaction_Time,Day_of_Week,Device_Type,Login_Location,Transaction_Status,Fraud_Flag,Remarks
203432,TXN00119880,CUST002997,Sachin Ali,Male,62.0,Accountant,25000.0,Salary,Dormant,Gold,...,Lucknow,Uttar Pradesh,2024-04-23,08:28:53,Tuesday,Tablet,Lucknow,Success,No,Transaction completed successfully
203433,TXN00103695,CUST002593,Ravi Menon,Female,43.0,Freelancer,50000.0,Current,Closed,Standard,...,Kochi,Kerala,2025-02-15,09:00:04,Saturday,Desktop,Kochi,Success,No,Transaction completed successfully
203434,TXN00131933,CUST003299,Akash Ali,Female,70.0,Retired,500000.0,Savings,Dormant,Premium,...,Pune,Maharashtra,2024-12-14,14:47:59,Saturday,Desktop,Pune,Success,Yes,Unusual pattern
203435,TXN00146868,CUST003672,Pooja Bhat,Female,33.0,Doctor,40000.0,Salary,Active,Standard,...,Hyderabad,Telangana,2025-01-29,08:34:16,Wednesday,Branch Terminal,Hyderabad,Success,No,Transaction completed successfully
203436,TXN00121959,CUST003049,Aravind Hussain,Female,56.0,Teacher,15000.0,Student,Closed,Standard,...,Bengaluru,Karnataka,2024-09-18,23:28:22,Wednesday,ATM,Bengaluru,Success,No,Transaction completed successfully

Understanding the data by the infermation

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 203437 entries, 0 to 203436
Data columns (total 32 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Transaction_ID       203437 non-null  str
 1   Customer_ID          203437 non-null  str
 2   Customer_Name        203437 non-null  str
 3   Gender               202219 non-null  str
 4   Age                  202308 non-null  float64
 5   Occupation           202257 non-null  str
 6   Monthly_Income       202243 non-null  float64
 7   Account_Type         202253 non-null  str
 8   Account_Status       202310 non-null  str
 9   Customer_Segment     202214 non-null  str
 10  Relationship_Years   202185 non-null  float64
 11  Loan_Customer        202335 non-null  str
 12  Credit_Score         202228 non-null  float64
 13  Transaction_Type     202356 non-null  str
 14  Transaction_Channel  202310 non-null  str
 15  Payment_Method       202329 non-null  str
 16  Merchant_Category    202281 non-null  str
 17  Transaction_Amount   202317 non-null  float64
 18  Account_Balance      202335 non-null  float64
 19  Currency             202332 non-null  str
 20  Branch               202268 non-null  str
 21  IFSC_Code            202304 non-null  str
 22  City                 203437 non-null  str
 23  State                203437 non-null  str
 24  Transaction_Date     202258 non-null  str
 25  Transaction_Time     202303 non-null  str
 26  Day_of_Week          202270 non-null  str
 27  Device_Type          202251 non-null  str
 28  Login_Location       202270 non-null  str
 29  Transaction_Status   202292 non-null  str
 30  Fraud_Flag           202334 non-null  str
 31  Remarks              202256 non-null  str
dtypes: float64(6), str(26)
memory usage: 49.7 MB

## Statistical Summary
for the numerical columns

In [8]:
df.describe()

,Age,Monthly_Income,Relationship_Years,Credit_Score,Transaction_Amount,Account_Balance
count,202308.000000,202243.000000,202185.000000,202228.000000,202317.000000,2.023350e+05
mean,46.542771,114420.993557,15.125573,600.633320,88453.213754,4.912976e+05
std,16.759691,137138.288882,8.893822,173.573135,102824.768056,9.806721e+05
min,18.000000,10000.000000,0.000000,300.000000,500.000000,0.000000e+00
25%,32.000000,25000.000000,8.000000,450.000000,24373.000000,0.000000e+00
50%,46.000000,50000.000000,15.000000,596.000000,47650.000000,0.000000e+00
75%,61.000000,150000.000000,23.000000,754.000000,110794.000000,4.990860e+05
max,75.000000,500000.000000,30.000000,900.000000,499996.000000,6.641153e+06

In [9]:
df.shape

(203437, 32)

In [10]:
df.columns.tolist()

['Transaction_ID',
 'Customer_ID',
 'Customer_Name',
 'Gender',
 'Age',
 'Occupation',
 'Monthly_Income',
 'Account_Type',
 'Account_Status',
 'Customer_Segment',
 'Relationship_Years',
 'Loan_Customer',
 'Credit_Score',
 'Transaction_Type',
 'Transaction_Channel',
 'Payment_Method',
 'Merchant_Category',
 'Transaction_Amount',
 'Account_Balance',
 'Currency',
 'Branch',
 'IFSC_Code',
 'City',
 'State',
 'Transaction_Date',
 'Transaction_Time',
 'Day_of_Week',
 'Device_Type',
 'Login_Location',
 'Transaction_Status',
 'Fraud_Flag',
 'Remarks']

In [11]:
df.dtypes

Transaction_ID             str
Customer_ID                str
Customer_Name              str
Gender                     str
Age                    float64
Occupation                 str
Monthly_Income         float64
Account_Type               str
Account_Status             str
Customer_Segment           str
Relationship_Years     float64
Loan_Customer              str
Credit_Score           float64
Transaction_Type           str
Transaction_Channel        str
Payment_Method             str
Merchant_Category          str
Transaction_Amount     float64
Account_Balance        float64
Currency                   str
Branch                     str
IFSC_Code                  str
City                       str
State                      str
Transaction_Date           str
Transaction_Time           str
Day_of_Week                str
Device_Type                str
Login_Location             str
Transaction_Status         str
Fraud_Flag                 str
Remarks                    str
dtype: object

# Find the missing value

In [12]:
df.isnull().sum()

Transaction_ID            0
Customer_ID               0
Customer_Name             0
Gender                 1218
Age                    1129
Occupation             1180
Monthly_Income         1194
Account_Type           1184
Account_Status         1127
Customer_Segment       1223
Relationship_Years     1252
Loan_Customer          1102
Credit_Score           1209
Transaction_Type       1081
Transaction_Channel    1127
Payment_Method         1108
Merchant_Category      1156
Transaction_Amount     1120
Account_Balance        1102
Currency               1105
Branch                 1169
IFSC_Code              1133
City                      0
State                     0
Transaction_Date       1179
Transaction_Time       1134
Day_of_Week            1167
Device_Type            1186
Login_Location         1167
Transaction_Status     1145
Fraud_Flag             1103
Remarks                1181
dtype: int64

Identyfy the duplicate records

In [13]:
df.duplicated().sum()

np.int64(2527)

### Remove the Duplicate

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
df.isnull().sum().sum()

np.int64(31181)

# Handling the columns wise missing value

In [16]:
df['Gender'].mode()

0    Male
Name: Gender, dtype: str

In [17]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [18]:
df['Gender'].isnull().sum()

np.int64(0)

In [19]:
df['Age'].median()

np.float64(46.0)

In [20]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [21]:
df["Age"].isnull().sum()

np.int64(0)

In [22]:
df['Occupation'].mode()

0    Financial Advisor
Name: Occupation, dtype: str

In [23]:
df['Occupation'] = df['Occupation'].fillna(df['Occupation'].mode()[0])

In [24]:
df.isnull().sum()

Transaction_ID            0
Customer_ID               0
Customer_Name             0
Gender                    0
Age                       0
Occupation                0
Monthly_Income         1194
Account_Type           1184
Account_Status         1127
Customer_Segment       1223
Relationship_Years     1252
Loan_Customer          1102
Credit_Score           1209
Transaction_Type       1081
Transaction_Channel    1127
Payment_Method         1108
Merchant_Category      1156
Transaction_Amount     1120
Account_Balance        1102
Currency               1105
Branch                 1169
IFSC_Code              1133
City                      0
State                     0
Transaction_Date       1179
Transaction_Time       1134
Day_of_Week            1167
Device_Type            1186
Login_Location         1167
Transaction_Status     1145
Fraud_Flag             1103
Remarks                1181
dtype: int64

In [25]:
df['Monthly_Income'] = df['Monthly_Income'].fillna(df['Monthly_Income'].median())
df['Account_Type'] = df['Account_Type'].fillna(df['Account_Type'].mode()[0])
df['Transaction_Type'] = df['Transaction_Type'].fillna(df['Transaction_Type'].mode()[0])
df['Account_Status'] = df['Account_Status'].fillna(df['Account_Status'].mode()[0])
df['Transaction_Amount'] = df['Transaction_Amount'].fillna(df['Transaction_Amount'].median())
df['Account_Balance'] = df['Account_Balance'].fillna(df['Account_Balance'].median())

In [26]:
df.isnull().sum()

Transaction_ID            0
Customer_ID               0
Customer_Name             0
Gender                    0
Age                       0
Occupation                0
Monthly_Income            0
Account_Type              0
Account_Status            0
Customer_Segment       1223
Relationship_Years     1252
Loan_Customer          1102
Credit_Score           1209
Transaction_Type          0
Transaction_Channel    1127
Payment_Method         1108
Merchant_Category      1156
Transaction_Amount        0
Account_Balance           0
Currency               1105
Branch                 1169
IFSC_Code              1133
City                      0
State                     0
Transaction_Date       1179
Transaction_Time       1134
Day_of_Week            1167
Device_Type            1186
Login_Location         1167
Transaction_Status     1145
Fraud_Flag             1103
Remarks                1181
dtype: int64

In [27]:
df["Customer_Segment"] =df["Customer_Segment"].fillna(df["Customer_Segment"].mode()[0])

In [28]:
df['Relationship_Years'] =df['Relationship_Years'].fillna(df['Relationship_Years'].median())

In [29]:
df['Loan_Customer'] = df['Loan_Customer'].fillna(df['Loan_Customer'].mode()[0])
df['Transaction_Channel'] = df['Transaction_Channel'].fillna(df['Transaction_Channel'].mode()[0])
df['Payment_Method'] = df['Payment_Method'].fillna(df['Payment_Method'].mode()[0])
df['Merchant_Category'] = df['Merchant_Category'].fillna(df['Merchant_Category'].mode()[0])
df['Currency'] = df['Currency'].fillna(df['Currency'].mode()[0])
df['Branch'] = df['Branch'].fillna(df['Branch'].mode()[0])
df['Transaction_Date'] = df['Transaction_Date'].fillna(df['Transaction_Date'].mode()[0])
df['Transaction_Time'] = df['Transaction_Time'].fillna(df['Transaction_Time'].mode()[0])
df['Day_of_Week'] = df['Day_of_Week'].fillna(df['Day_of_Week'].mode()[0])
df['Device_Type'] = df['Device_Type'].fillna(df['Device_Type'].mode()[0])
df['Login_Location'] = df['Login_Location'].fillna(df['Login_Location'].mode()[0])

In [30]:
df['Transaction_Status'] = df['Transaction_Status'].fillna(df['Transaction_Status'].mode()[0])
df['Fraud_Flag'] = df['Fraud_Flag'].fillna(df['Fraud_Flag'].mode()[0])

In [31]:
df['Credit_Score'] = df['Credit_Score'].fillna(df['Credit_Score'].median())
df['Remarks'] = df['Remarks'].fillna(df['Remarks'].mode()[0])

In [32]:
df.isnull().sum()

Transaction_ID            0
Customer_ID               0
Customer_Name             0
Gender                    0
Age                       0
Occupation                0
Monthly_Income            0
Account_Type              0
Account_Status            0
Customer_Segment          0
Relationship_Years        0
Loan_Customer             0
Credit_Score              0
Transaction_Type          0
Transaction_Channel       0
Payment_Method            0
Merchant_Category         0
Transaction_Amount        0
Account_Balance           0
Currency                  0
Branch                    0
IFSC_Code              1133
City                      0
State                     0
Transaction_Date          0
Transaction_Time          0
Day_of_Week               0
Device_Type               0
Login_Location            0
Transaction_Status        0
Fraud_Flag                0
Remarks                   0
dtype: int64

Drop for null value in IFSC_Code column

In [33]:
df = df.dropna(subset=['IFSC_Code'])

## Finally Handled the missing value

In [34]:
df.isnull().sum()

Transaction_ID         0
Customer_ID            0
Customer_Name          0
Gender                 0
Age                    0
Occupation             0
Monthly_Income         0
Account_Type           0
Account_Status         0
Customer_Segment       0
Relationship_Years     0
Loan_Customer          0
Credit_Score           0
Transaction_Type       0
Transaction_Channel    0
Payment_Method         0
Merchant_Category      0
Transaction_Amount     0
Account_Balance        0
Currency               0
Branch                 0
IFSC_Code              0
City                   0
State                  0
Transaction_Date       0
Transaction_Time       0
Day_of_Week            0
Device_Type            0
Login_Location         0
Transaction_Status     0
Fraud_Flag             0
Remarks                0
dtype: int64

In [35]:
df.duplicated().sum()

np.int64(217)

In [36]:
df = df.drop_duplicates()

In [37]:
df.info()

<class 'pandas.DataFrame'>
Index: 199560 entries, 0 to 203436
Data columns (total 32 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Transaction_ID       199560 non-null  str
 1   Customer_ID          199560 non-null  str
 2   Customer_Name        199560 non-null  str
 3   Gender               199560 non-null  str
 4   Age                  199560 non-null  float64
 5   Occupation           199560 non-null  str
 6   Monthly_Income       199560 non-null  float64
 7   Account_Type         199560 non-null  str
 8   Account_Status       199560 non-null  str
 9   Customer_Segment     199560 non-null  str
 10  Relationship_Years   199560 non-null  float64
 11  Loan_Customer        199560 non-null  str
 12  Credit_Score         199560 non-null  float64
 13  Transaction_Type     199560 non-null  str
 14  Transaction_Channel  199560 non-null  str
 15  Payment_Method       199560 non-null  str
 16  Merchant_Category    199560 non-null  str
 17  Transaction_Amount   199560 non-null  float64
 18  Account_Balance      199560 non-null  float64
 19  Currency             199560 non-null  str
 20  Branch               199560 non-null  str
 21  IFSC_Code            199560 non-null  str
 22  City                 199560 non-null  str
 23  State                199560 non-null  str
 24  Transaction_Date     199560 non-null  str
 25  Transaction_Time     199560 non-null  str
 26  Day_of_Week          199560 non-null  str
 27  Device_Type          199560 non-null  str
 28  Login_Location       199560 non-null  str
 29  Transaction_Status   199560 non-null  str
 30  Fraud_Flag           199560 non-null  str
 31  Remarks              199560 non-null  str
dtypes: float64(6), str(26)
memory usage: 50.2 MB

In [40]:
df['Transaction_Date'].unique()

<StringArray>
['2025-12-18', '2024-04-19', '2025-02-11', '2024-07-24', '2024-02-25',
 '2025-05-04', '2025-09-08', '2025-09-25', '2024-07-18', '2024-09-26',
 ...
 '2024-12-11', '2024-09-12', '2025-06-04', '2025-01-22', '2024-12-12',
 '2025-08-13', '2024-03-13', '2025-05-09', '2025-05-19', '2024-01-25']
Length: 730, dtype: str

In [45]:
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'], format='%Y-%m-%d')

In [41]:
df["Transaction_Time"].unique()

<StringArray>
['11:22:53', '06:31:56', '22:46:47', '06:46:40', '20:53:05', '16:00:51',
 '15:07:21', '17:01:15', '10:40:32', '20:59:35',
 ...
 '14:21:14', '16:00:47', '09:32:28', '22:51:27', '08:08:28', '11:26:42',
 '11:33:11', '13:37:30', '09:19:08', '20:42:28']
Length: 61738, dtype: str

In [49]:
df["Transaction_Time"] = pd.to_datetime(df["Transaction_Time"], format='%H:%M:%S')

In [50]:
df.dtypes

Transaction_ID                    str
Customer_ID                       str
Customer_Name                     str
Gender                            str
Age                           float64
Occupation                        str
Monthly_Income                float64
Account_Type                      str
Account_Status                    str
Customer_Segment                  str
Relationship_Years            float64
Loan_Customer                     str
Credit_Score                  float64
Transaction_Type                  str
Transaction_Channel               str
Payment_Method                    str
Merchant_Category                 str
Transaction_Amount            float64
Account_Balance               float64
Currency                          str
Branch                            str
IFSC_Code                         str
City                              str
State                             str
Transaction_Date       datetime64[us]
Transaction_Time       datetime64[us]
Day_of_Week                       str
Device_Type                       str
Login_Location                    str
Transaction_Status                str
Fraud_Flag                        str
Remarks                           str
dtype: object

In [51]:
df["Gender"].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [52]:
df["Account_Type"].unique()

<StringArray>
['Savings', 'Student', 'Salary', 'Current']
Length: 4, dtype: str

In [53]:
df["Transaction_Status"].unique()

<StringArray>
['Success', 'Failed', 'Pending']
Length: 3, dtype: str

## Export the data

In [54]:
df.to_csv(r"banking_transactions_200k_cleaned.csv", index=False)